name: Update Predictions Daily

on:
  schedule:
    # Θα τρέχει αυτόματα κάθε μέρα στις 05:00 το πρωί και στις 13:00 το μεσημέρι (Ώρα Ελλάδας)
    - cron: '0 3,11 * * *'
  workflow_dispatch: # Σου επιτρέπει να το τρέχεις χειροκίνητα όποτε θες εσύ

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/python-v3@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run prediction model
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add daily_predictions.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update predictions" && git push)
